services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
        POSTGRES_USER: canturgut
        POSTGRES_PASSWORD: canturgut
        POSTGRES_DB: can_db